use_default_settings:
  engines:
    keep_only:
      - google
      - brave
      - qwant
      - mojeek

search:
  formats:
    - html
    - json

server:
  secret_key: "replace-with-a-long-random-secret"
  limiter: false
  image_proxy: false
