name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build -t fair-core-tests:latest .
      - name: Run tests
        run: |
          docker run --rm --env FAIRSHARING_KEY=${{ secrets.FAIRSHARING_KEY }} fair-core-tests:latest bundle exec rspec
          